name: CLb0
version: '${project.version}'
main: com.bobobo.plugins.clb0.CLb
api-version: '1.16'
commands:
  clb0:
    description: Main command for CLb0 plugin
    aliases: [creative-log]
    permission: clb0.use
    usage: /<command> reload
