name: CLb0
version: '${project.version}'
main: com.bobobo.plugins.clb0.CLb
api-version: '1.16'
depend: [packetevents]
commands:
  clb0:
    description: Main command for CLb0 plugin
    aliases: [creative-log]
    usage: /<command> reload
permissions:
  clb0.reload:
    description: Allows reloading the CLb0 plugin configuration
    default: op